### PR TITLE
CC-275 printf placeholder

### PR DESCRIPTION
**Pull request by Oceas**
CC-275

Description

- Add `noopener noreferrer` to blank links.
- Refactor multiple translated strings.

### CODE REVIEW

**Review by richaber — CHANGES_REQUESTED** [review]
Nice work @Oceas. I have a couple of minor changes, but overall nice job unpacking that. 

Making a note here that there are a few lines in class-notification-content.php that could use some attention, but it's a little complex, and I don't know if we want to spend the time on unravelling it right now.

https://github.com/WebDevStudios/constant-contact-forms/blob/1.12.0/includes/class-notification-content.php#L234-L255

screenshot

**Comment by Oceas** [comment]
Recommendations requested have been implemented.

**Comment by Oceas** [comment]
> Nice work @Oceas. I have a couple of minor changes, but overall nice job unpacking that.
> 
> Making a note here that there are a few lines in class-notification-content.php that could use some attention, but it's a little complex, and I don't know if we want to spend the time on unravelling it right now.
> 
> https://github.com/WebDevStudios/constant-contact-forms/blob/1.12.0/includes/class-notification-content.php#L234-L255
> 
> screenshot

Given that it's simply a link that can already be configured I do not find much value in spending time to unravel it.

**Review by richaber — APPROVED** [review]
Nice work @Oceas 👍

**Pull request merged**
