### PR TITLE
Feature/cc 393 remove frontend jquery

### PR DESCRIPTION
**Pull request by tw2113**

### CODE REVIEW

**Comment by tw2113** [comment]
@DavesjoshinWDS definitely understand if you want/need extra FEE eyes on this one, it's pretty much all Javascript.

**Comment by DavesjoshinWDS** [comment]
@tw2113 There might be a couple things to take a closer look at. Hard to tell if related to this update. 

1. I submitted a simple form with (first, last name, email and address). It submitted fine but did displaying an error in the console when submitting. (screenshot)
DevTools_-_constant-contact-forms_local_sample-page_
Cursor_and_DevTools_-_constant-contact-forms_local_sample-page__and_constant-contact-forms

2. I submitted a full form (all available fields) and it gets stuck on submitting and throws this error
DevTools_-_constant-contact-forms_local_full-form_

**Comment by tw2113** [comment]
@DavesjoshinWDS

What is your ajax/"no refresh" setting?
Any fields besides email marked as required?
I assume you filled in all the fields?
Any other forms besides the one you're using, embedded in the page? for example in the footer or a sidebar?

**Comment by DavesjoshinWDS** [comment]
@tw2113 
1. This had 3 required fields, First name, Last name, and Address. It only produces the error after you click submit, even if all the fields are satisfied. Only one form on the page.

2. I'm having trouble getting this error again. In fact, it threw the same error as #1 (above). This has 2 required fields, First name and a custom text area. 
Full_Form_–_Constant_Contact_Forms

**Comment by DavesjoshinWDS** [comment]
Issues resolved after syncing, unrelated build issue.

**Review by DavesjoshinWDS — APPROVED** [review]

**Pull request merged**
