### PR TITLE
Feature/cc 409 admin dejquery

### PR DESCRIPTION
**Pull request by tw2113**
This PR removes MOST of the jQuery integration that we had with the admin side of our plugin interaction and functionality.

There are a couple spots that rely on CMB2 jQuery-based events that I had to leave in place with the builder.js file. If we decide long term to move away from CMB2, we can address at that time, but that is a much larger project than what we presently do.

There is also a spot using jQuery UI Dialog with the `modal.js` file regarding log deletion confirmation that we're leaving as jQuery for the time being.

Only the files in the `assets/js/ctct-plugin-admin/` need to be reviewed, the others are build files, sourced from that folder.

### CODE REVIEW

**Comment by tw2113** [comment]
If we run into build file issues, merge anyway and we can re-run npm scripts afterwards.

**Comment by lindseywb** [comment]
Great work so far! The common thing that I see is getting the `let` vs `const` issues fixed.

**Comment by tw2113** [comment]
@lindseywb regarding `let` vs `const` are you thinking pick one and stick to that keyword as much as possible? Or perhaps "any that aren't getting re-assigned ever, go with const. If they are being re-assigned later, no problem with let" ?

**Comment by lindseywb** [comment]
@tw2113 if the value is not being reassigned, they should be `const`. Otherwise, they should be `let`.

**Review by lindseywb — APPROVED** [review]
Const-quest complete, looks like you got them all!

**Pull request merged**
