### PR TITLE
CC-36: Allow users to choose list

### PR DESCRIPTION
**Pull request by ravewebdev**
Ticket: [CC-36](https://webdevstudios.atlassian.net/browse/CC-36)

### Description ###

Updates admin and frontend form display to allow list options to customer:
- Changes admin list selection to multi-checkbox.
- Updates frontend list display:
    - Separates list input from "opt-in" checkbox/text.
    - Displays checkboxes for each list selected in admin.
- Updates contact submission process to handle multiple lists.
- Updates admin forms listing to display potentially multiple lists in list column.

### Screenshot ###

Screen Shot 2020-07-06 at 4 54 02 PM

### Steps to verify the solution ###

1. Edit form in admin and confirm a) list selection now display as a checkbox, and b) previous list selection is automatically checked.
2. In admin forms listing, confirm all forms display appropriate list(s) in the list column.
3. On the frontend, confirm a) edited form displays all list options selected in admin as checkboxes, and b) opt-in checkbox is separate from list selection.
4. Attempt to submit form without selecting a list and confirm error message appears.
5. Submit form with a) one list selected, then b) again with more than one list selected.
6. Edit form in admin to select only a single list.
7. On the frontend, confirm single checkbox is hidden but still exists, then submit form.
6. Log into Constant Contact account and confirm a) submissions were successful, and b) contact was added to all lists selected. (Note: Selecting "Bypass Constant Contact cron scheduling" in Contact Form settings is useful to avoid delays in submission.)

### CODE REVIEW

**Comment by tw2113** [comment]
One thing I can already predict is going to present trouble is sheer volume of lists that some people have. My local install has access to 12, but I would not be surprised at all if some site owners have considerably more.

This leaves me wondering if we should handle the list selection with a different field type, perhaps mutliselect instead of multicheck, or if anything, add in some custom CSS to set a max height and then `overflow: scroll` or similar. If we want to get super fancy, something to help with list selection like select2 would be useful, but I don't want to add too much overhead where possible.

More notes coming soon.

**Comment by tw2113** [comment]
Not sure if something in my setup, or something else, but it's not letting me submit at all. It'll disable the submit briefly but never go anywhere with the AJAX integration.

Non ajax is working, and I was added to both lists chosen, with both reCAPTCHA 2 and without. so there's some good hope there.

What are your thoughts on defaults? Perhaps auto-check the first one listed, for both in the admin and the user-facing? Also on the admin, while I mention some users may have a huge amount of lists, some may only have zero or one at the time. Perhaps we should output some messaging for zero lists and a link to get one started? For people with only one, auto-check it for them.

For user facing, I'm kind of thinking just no checkbox output if there's only 1 list created, just have it submit as we have now. However, one we get to 2+, then we show the checkboxes and also auto-check any specified default.

**Comment by ravewebdev** [comment]
@tw2113 
> This leaves me wondering if we should handle the list selection with a different field type, perhaps mutliselect instead of multicheck, or if anything, add in some custom CSS to set a max height and then overflow: scroll or similar. If we want to get super fancy, something to help with list selection like select2 would be useful, but I don't want to add too much overhead where possible.

CMB2 does not appear to natively support multi-select fields. Is there a library you could recommend we look into? I initially found [this select2 extension](https://github.com/mustardBees/cmb-field-select2), but it has not been updated in 4 years.

> What are your thoughts on defaults? Perhaps auto-check the first one listed, for both in the admin and the user-facing?

I would vote no on this, at least on the admin side. This would defeat the purpose of saving previously-saved list settings for existing forms. And the previous functionality allowed no list to be selected as well. For user-facing, though, that shouldn't be an issue.

> Also on the admin, while I mention some users may have a huge amount of lists, some may only have zero or one at the time. Perhaps we should output some messaging for zero lists and a link to get one started? For people with only one, auto-check it for them.

Is it possible to have zero lists? I'm unable to fully remove all lists from my CC account to test this. After deleting all lists, then reloading, a new list appears.

> For user facing, I'm kind of thinking just no checkbox output if there's only 1 list created, just have it submit as we have now. However, one we get to 2+, then we show the checkboxes and also auto-check any specified default.

I'll try this out and make sure it doesn't introduce any errors.

**Comment by ravewebdev** [comment]
@tw2113 latest changes:
- First checkbox on frontend is auto-checked.
- List selection is hidden if one or fewer list options are displayed.

**Comment by tw2113** [comment]
For the moment, lets tinker with the CSS route and see how things play out. We can get feedback and whatnot afterwards and see if we want to pivot to something else. I'm also curious if Yoast still ships with a select2 instance, and if yes, we could make use of it. Marketing + SEO go hand in hand, so I suspect we would have a pretty high success rate.

I did momentarily forget that we don't output anything if there's no connected account, and once someone does get an account, or if they already have one, they're going to have a list soon if not already. So I'm fine with no default on the admin.

In terms of lists on the site owner's side, it may not necessarily be possible to have zero lists, as it likely regularly sync's up with their constant contact account. However, if the CC account has no lists yet, then there's nothing to sync.

**Comment by ravewebdev** [comment]
@tw2113 I've added styling for the checkboxes. Screenshots below as the site refuses to easily show updated styling given the stylesheet versioning.

admin view:
Screen Shot 2020-07-08 at 9 32 08 AM

frontend view:
Screen Shot 2020-07-08 at 9 37 28 AM

**Comment by tw2113** [comment]
Hey Rebekah,

Are we showing all available lists in both places? It may have been lost in translation, but at least with what I had in mind with the original enhancement is that all the lists are shown for the admin, to choose which should show to the user to select. Then on the frontend, only those chosen would be listed.

**Comment by richaber** [comment]
> Are we showing all available lists in both places? It may have been lost in translation, but at least with what I had in mind with the original enhancement is that all the lists are shown for the admin, to choose which should show to the user to select. Then on the frontend, only those chosen would be listed.

I only have 2 lists, but it shows them in the Admin for me...
Screen Shot 2020-07-08 at 2 01 15 PM

How many lists do _you_ have?

**Comment by ravewebdev** [comment]
@tw2113 
> Are we showing all available lists in both places? It may have been lost in translation, but at least with what I had in mind with the original enhancement is that all the lists are shown for the admin, to choose which should show to the user to select. Then on the frontend, only those chosen would be listed.

Nope, the frontend just shows whatever lists were selected in the admin. My screenshots were just confusing, because _after_ I took the first (admin) screenshot, I selected all lists so I could test styling on the frontend.

**Comment by tw2113** [comment]
Noted. I'm wondering how much we're going to need this styling for the frontend, because i assume people aren't going to go hog wild with lists to choose from. Most will probably stay as is, for example.

**Comment by richaber** [comment]
@tw2113 where did we land on this?
Is it good to merge, or does it require changes?
(We also probably need to change the branch we're merging into, since the sprint is different)

**Comment by tw2113** [comment]
I want to give it a bit more tire kicking just in case, but haven't had a chance to circle back just yet.

**Comment by tw2113** [comment]
I did a rebase of master on the branch and a `--force-with-lease` so it's caught up with our releases.

**Comment by tw2113** [comment]
Fresh feedback.

1. Let's not have "Select list(s) to subscribe to" be wrapped up a label and whatnot. It's creating a label with no associated field, and it's also being affected by label placement code.
2. How easy, or difficult do you think it'd be to provide a way for the user to set the a default? Would it be worth it? As is, it's being displayed in the order found in the admin, and then checking the first one. Not bad by any means, but I could see some potential frustration with that too.
3. I feel like we should provide some small styles or notes to help illustrate that there may be a scrollable area depending on their list size. It may not be obvious or apparent that that spot will scroll if there's enough elements.

**Comment by ravewebdev** [comment]
@tw2113 can you clarify your latest comment?

> Let's not have "Select list(s) to subscribe to" be wrapped up a label and whatnot. It's creating a label with no associated field, and it's also being affected by label placement code.

What would you propose? I can remove the label element itself, but then the text is just wrapped in a span, causing new display issues. We could switch to a plain heading or paragraph element, would that work?

> How easy, or difficult do you think it'd be to provide a way for the user to set the a default? Would it be worth it? As is, it's being displayed in the order found in the admin, and then checking the first one. Not bad by any means, but I could see some potential frustration with that too.

Set a default where / how? I believe we already decided to just auto-check the first listed; otherwise, that sounds like a more complex feature request we'd probably want to run by the client and implement as a separate ticket, as it could be more convoluted than useful if it's not a feature many people will likely use.

> I feel like we should provide some small styles or notes to help illustrate that there may be a scrollable area depending on their list size. It may not be obvious or apparent that that spot will scroll if there's enough elements.

Can you elaborate on this? Specifically, do you mean in the admin, frontend, or both, and do you have an example of what styles or notes we could implement?

**Comment by tw2113** [comment]
**We could switch to a plain heading or paragraph element, would that work?**
Yes, let's see where that goes and how it looks.

**Set a default where / how?**
It likely would be, so we may need to see how this feature goes over with users. Basically the site owner may not want the first one listed to be default, but we're set to kind of force that a little, thus why I was wondering if we could allow the site owner to say "this one is default, when multiple are available". Alternatively, maybe we should NOT check one after all, and just let the user choose with the field being a required field.

Also perhaps something we should pass back to Patrick and team, to see what they think.

**Can you elaborate on this? Specifically, do you mean in the admin, frontend, or both, and do you have an example of what styles or notes we could implement?**
In the admin only, as I assume site owners are not going to list EVERYTHING for the frontend, and if they do, they can handle themselves a bit.

Perhaps something like https://css-scroll-shadows.now.sh/?bgColor=3821ed&shadowColor=222222&pxSize=15

**Comment by ravewebdev** [comment]
@tw2113 

After doing a bit of digging, I found some sources recommending using `fieldset` and `legend` for multi-checkbox lists, so I went with that, then styled to remove some of the extra bulky styles that added. I also removed the scrolling on the frontend, so it should just display the full list of options selected in the admin.

Screen Shot 2020-08-04 at 3 59 49 PM

In terms of default for the frontend, I'd recommend we leave as-is and get the client's feedback as to how to proceed/modify from there.

I've added some scroll shadows to the admin (top bar only appears if there's space to scroll up, bottom bar only appears if there's space to scroll down).

Screen Shot 2020-08-04 at 4 02 41 PM

**Comment by tw2113** [comment]
Lets roll with this. We can always adjust and pivot and tweak as feedback comes in. The core functionality, which is getting the user sent to the API and the lists is working and these latest changes won't affect that.

**Comment by tw2113** [comment]
I just noticed that we are not receiving a value for the `ctct-opt-in` checkbox field type. Previous to this PR, it's receiving the list ID value for the corresponding Constant Contact list a form is associated to.

It is a value checked for in the form processing, as part of an if/else block.

However, it's most used in the class-mail.php file for some parts. We'll want to find a way to store as valid string but still find a way to separate out by accurate ID values.

**Comment by ravewebdev** [comment]
@tw2113 in terms of list ID handling, the `ctct-opt-in` field was replaced with an array generated from the combined `lists` checkbox inputs ("Separates list input from "opt-in" checkbox/text."). At this point, the `ctct-opt-in` field holds a boolean `true` value to ensure the manual optin is checked (if required for the form).

**Pull request merged**
